### ISSUE TITLE
Can't travel while matrix is running

### ISSUE THREAD

**Issue by tyrope** [mynameisneo7/bitburner-scripts#2]
Running Matrix.js will prevent the following things to be clickable:
* Any faction names in the Factions screen.
* Locations (City view, ASCII mode)
* Cities (Travel view, ASCII mode)

**Comment by mynameisneo7** [comment]
Should be fixed in 70d2094 now. Should only need to download matrix.js and restart the script.

One known issue though is the Factions screen doesn't change the mouse pointer (at least for me) to hand, but hover/clicks still work normally.
